name: Run Swing Trade Screener

on:
  schedule:
    - cron: '30 10 * * 1-5'   # Weekdays 4:00 PM IST
    - cron: '30 11 * * 0'     # Sunday 5:00 PM IST
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Screener
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_SHEET_JSON: ${{ secrets.GOOGLE_SHEET_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          echo "$GOOGLE_SHEET_JSON" > creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=creds.json
          python screener.py
