name: Run Swing Trade Screener

on:
  schedule:
    # Every weekday at 4:00 PM IST (10:30 UTC)
    - cron: '30 10 * * 1-5'
    # Sunday at 5:00 PM IST (11:30 UTC)
    - cron: '30 11 * * 0'
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Screener
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_SHEET_JSON: ${{ secrets.GOOGLE_SHEET_JSON }}
        run: |
          echo "$GOOGLE_SHEET_JSON" > creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=creds.json
          python screener.py
